server:
  port: 9999
  servlet:
    context-path: /etl
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3333/etl?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  web:
    resources:
      static-locations: classpath:/static/,file:${photo.file.dir} #暴露哪些资源可以通过项目名访问
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 120MB
mybatis:
  mapper-locations: classpath:com/yuanfang/mapper/*.xml  #指定mapper配置文件位置
  type-aliases-package: com.yuanfang.entity  #指定实体类的别名 默认：类名首字母小写
# 日志配置
logging:
  level:
    root: info #全局日志级别
    com.yuanfang: debug #指定包日志级别
photo:
  file:
    dir: F:\SBProjects\ems-thymeleaf\photos
